name: Build and Deploy .Net Application
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Execute dotnet
        run: dotnet build github4women